spring.application.name=ai-api-testing-agent

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_api_testing_agent
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true